version: '3.8'

services:
  app:
    build: .
    container_name: tinyurl-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./src:/app           # Mount the local src folder to /app in the container
      - /app/node_modules    # Avoids overwriting node_modules
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"

  db:
    image: postgres:alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persist database data

volumes:
  pgdata:  # Named volume for PostgreSQL data persistence
